### ISSUE TITLE
SSR-Net keras model to ONNX conversion failed. 

### ISSUE THREAD

**Issue by ghimiredhikura** [bleakie/MaskInsightface#17]
Hi @bleakie,

Congratulations for the nice work. 

I am trying to use SSR-Net pretrained model in ncnn for edge device inference. For that I need to convert this model to onnx. However with this [keras2onnx](https://github.com/onnx/keras-onnx) converter i am facing following trouble. 

```
(ghimire36) C:\Users\ghimire\Desktop\keras2onnx>python keras_onnx.py
Traceback (most recent call last):
  File "keras_onnx.py", line 7, in <module>
    model = load_model('ssrnet_3_3_3_112_0.75_1.0.h5')
  File "C:\ProgramData\Anaconda3\envs\ghimire36\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 143, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\ProgramData\Anaconda3\envs\ghimire36\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 159, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
```

**keras_onnx.py**
```
from tensorflow.python.keras.models import load_model
import onnx
import keras2onnx

onnx_model_name = 'ssrnet_3_3_3_112_0.75_1.0.onnx'

model = load_model('ssrnet_3_3_3_112_0.75_1.0.h5')
onnx_model = keras2onnx.convert_keras(model, model.name)
keras2onnx.save_model(onnx_model, onnx_model_name)
```

Any help will be highly appreciated! 

Thanks.

**Comment by bleakie** [comment]
Make sure your model file path is correct.
